# Generated by Django 4.1.6 on 2023-02-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasabiHomepage', '0002_menu_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='starterMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
